name:                study-report
version:             0.1.0.0
github:              "logicoffee/study-report"
license:             BSD3
author:              "Ryo Iketani"
maintainer:          "riemann1618@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/logicoffee/study-report#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  study-report:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - study-report

tests:
  study-report-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - study-report
