name:                spicy
version:             0.1.0.0
github:              "logicoffee/scotty_test"
license:             BSD3
author:              "Ryo Iketani"
maintainer:          "riemann1618@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/logicoffee/scotty_test#readme>

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - text
  - scientific
  - aeson
  - scotty
  - HDBC
  - HDBC-postgresql
  - persistable-record
  - relational-query-HDBC
  - relational-query
  - product-isomorphic
  - cryptonite

library:
  source-dirs: src

executables:
  spicy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spicy

tests:
  spicy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spicy
      - bytestring
      - hspec
      - hspec-wai
      - http-types
      - wai-extra
